ASR_LOOP: True
ASR_ON: "False"
sentence1: "find a person, memorize the person and recognize him"
sentence6: "grasp the coke bring the coke to business and tell something about yourself" 
sentence: "bring me a drink"
sentence11: "bring the coke to a sofa"
sentence2: "bring a coke to the business bring a coke to the business bring a coke to the business "
