locations: ["bench", "hallway_table", "hanger", "umbrella_stand", "bar", "side_table", "kitchen_table", "kitchen_counter", "stove", "trash_bin", "cupboard", "sink", "fridge", "bed", "dresser", "sideboard", "bedside_table", "bookshelf", "pantry", "cabinet", "dinner_table", "couch_table", "arm_chair", "sofa", "tv_counter",  "plant", "exit", "referee"]

items: ["deodorant", "tooth_paste", "cleaner", "fresh_discs", "fanta", "beer_can", "coke", "sponge", "seven_up", "chocolate_milk", "tomato_sauce", "energy_drink", "peanut_butter", "chicken_noodles", "orange_juice", "milk", "apple_juice", "veggie_noodles", "garlic_sauce", "chocolate", "cookies", "drops", "crackers", "marmalade"]

persons: ["albert", "homer", "jordi", "karen", "ricardo", "referee", "Michael", "Christopher", "Matthew", "Joshua", "David", "James", "Daniel", "Robert", "John", "Joseph", "Jessica", "Jennifer", "Amanda", "Ashley", "Sarah", "Stephanie", "Melissa", "Nicole", "Elizabeth", "Heather", "person"]

rooms: ["kitchen", "bedroom", "living room"]

room:
    kitchen: ["kitchen table"]
    living: ["sofa", "armchair", "bookshelf"]
    bedroom: ["sideboard", "bed", "drawer"]


location:
    charger: ["soda"]
    business: ["cheese", "beer"]
    kitchen: ["spoons", "glass"]


it_category:
        drink: ["beer bottle", "fanta", "beer can", "coke", "seven up", "chocolate milk", "energy drink", "orange juice", "milk", "apple juice"]
        food: [" tomato sauce", "peanut butter", "chicken noodles", "marmalade", "veggie noodles", "garlic sauce "]
        snack: [" chocolate", "cookies", "drops", "crackers"]
        cleaning_stuff: ["deodorant", "tooth paste", "cleaner", "fresh discs", "sponge"]

loc_category:
        table: [" hallway table", "side table", "kitchen table", "bedside table", "dinner table", "couch table"]
        shelf: ["bar", "kitchen counter", "cupboard", "dresser", "sideboard", "bookshelf", "pantry", "cabinet "]
        appliance: ["stove", "sink", "fridge", "tv counter"]
        utensils: ["hanger", "umbrella stand", "trash bin", "plant"]
        seat: ["bench", "bed", "arm chair", "sofa"]
        seating: ["bench", "bed", "arm chair", "sofa"]
        door: ["exit"]

